name: Add PNG File from Issue

on:
  issues:
    types: [opened]

jobs:
  add_png_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick wget
      
    - name: Download and Convert issue content to PNG
      run: |
        imageURL=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=\()(.+?)(?=\))')
        wget -O temp_image.jpg $imageURL
        convert temp_image.jpg "${{ github.event.issue.title }}.png"
        rm temp_image.jpg
      
    - name: Add PNG file to repository
      run: |
        git add "${{ github.event.issue.title }}.png"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Add PNG file for issue: #${{ github.event.issue.number }}"
        git push
