name: Add PNG File from Issue

on:
  issues:
    types: [opened]

jobs:
  add_png_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
      
    - name: Convert issue content to PNG
      run: |
        echo "${{ github.event.issue.body }}" | convert - "${{ github.event.issue.title }}.png"
      
    - name: Add PNG file to repository
      run: |
        git add "${{ github.event.issue.title }}.png"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Add PNG file for issue: #${{ github.event.issue.number }}"
        git push
